CREATE TABLE cars (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    year INT NOT NULL,
    make VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    category VARCHAR(20) NOT NULL,
    for_sale BOOLEAN NOT NULL,
    CONSTRAINT chk_year CHECK (year BETWEEN 1885 AND 2100)
);